package com.spj.demo.mapper;

import com.spj.demo.pojo.Brach;

public interface BrachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brach
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String brachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brach
     *
     * @mbggenerated
     */
    int insert(Brach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brach
     *
     * @mbggenerated
     */
    int insertSelective(Brach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brach
     *
     * @mbggenerated
     */
    Brach selectByPrimaryKey(String brachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brach
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Brach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brach
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Brach record);
}