package com.spj.demo.mapper;

import com.spj.demo.pojo.Info;

import java.util.List;

public interface InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated
     */
    int insert(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated
     */
    int insertSelective(Info record);
    List<Info> selectByStu(String stu_id);
}