package com.spj.demo.mapper;

import com.spj.demo.pojo.Teach;

public interface TeachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String teachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int insert(Teach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int insertSelective(Teach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    Teach selectByPrimaryKey(String teachId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Teach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Teach record);
}