package com.spj.demo.pojo;

public class Brach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brach.brach_id
     *
     * @mbggenerated
     */
    private String brachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brach.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brach.brach_id
     *
     * @return the value of brach.brach_id
     *
     * @mbggenerated
     */
    public String getBrachId() {
        return brachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brach.brach_id
     *
     * @param brachId the value for brach.brach_id
     *
     * @mbggenerated
     */
    public void setBrachId(String brachId) {
        this.brachId = brachId == null ? null : brachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brach.name
     *
     * @return the value of brach.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brach.name
     *
     * @param name the value for brach.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}