package com.spj.demo.pojo;

public class ClassR {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_id
     *
     * @mbggenerated
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.branch_id
     *
     * @mbggenerated
     */
    private String branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_id
     *
     * @return the value of class.class_id
     *
     * @mbggenerated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_id
     *
     * @param classId the value for class.class_id
     *
     * @mbggenerated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.name
     *
     * @return the value of class.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.name
     *
     * @param name the value for class.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.branch_id
     *
     * @return the value of class.branch_id
     *
     * @mbggenerated
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.branch_id
     *
     * @param branchId the value for class.branch_id
     *
     * @mbggenerated
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }
}