package com.spj.demo.pojo;

public class Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.course_id
     *
     * @mbggenerated
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.teach_id
     *
     * @mbggenerated
     */
    private String teachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.start_time
     *
     * @mbggenerated
     */
    private Integer startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.end_time
     *
     * @mbggenerated
     */
    private Integer endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.teach_name
     *
     * @mbggenerated
     */
    private String teachName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.say
     *
     * @mbggenerated
     */
    private String say;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.stu_id
     *
     * @return the value of info.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.stu_id
     *
     * @param stuId the value for info.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.course_id
     *
     * @return the value of info.course_id
     *
     * @mbggenerated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.course_id
     *
     * @param courseId the value for info.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.teach_id
     *
     * @return the value of info.teach_id
     *
     * @mbggenerated
     */
    public String getTeachId() {
        return teachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.teach_id
     *
     * @param teachId the value for info.teach_id
     *
     * @mbggenerated
     */
    public void setTeachId(String teachId) {
        this.teachId = teachId == null ? null : teachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.start_time
     *
     * @return the value of info.start_time
     *
     * @mbggenerated
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.start_time
     *
     * @param startTime the value for info.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.end_time
     *
     * @return the value of info.end_time
     *
     * @mbggenerated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.end_time
     *
     * @param endTime the value for info.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.teach_name
     *
     * @return the value of info.teach_name
     *
     * @mbggenerated
     */
    public String getTeachName() {
        return teachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.teach_name
     *
     * @param teachName the value for info.teach_name
     *
     * @mbggenerated
     */
    public void setTeachName(String teachName) {
        this.teachName = teachName == null ? null : teachName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.course_name
     *
     * @return the value of info.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.course_name
     *
     * @param courseName the value for info.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.say
     *
     * @return the value of info.say
     *
     * @mbggenerated
     */
    public String getSay() {
        return say;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.say
     *
     * @param say the value for info.say
     *
     * @mbggenerated
     */
    public void setSay(String say) {
        this.say = say == null ? null : say.trim();
    }
}