package com.spj.demo.pojo;

public class Link {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.course_id
     *
     * @mbggenerated
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.teach_id
     *
     * @mbggenerated
     */
    private String teachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.start_time
     *
     * @mbggenerated
     */
    private Integer startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.end_time
     *
     * @mbggenerated
     */
    private Integer endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.id
     *
     * @return the value of link.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.id
     *
     * @param id the value for link.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.stu_id
     *
     * @return the value of link.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.stu_id
     *
     * @param stuId the value for link.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.course_id
     *
     * @return the value of link.course_id
     *
     * @mbggenerated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.course_id
     *
     * @param courseId the value for link.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.teach_id
     *
     * @return the value of link.teach_id
     *
     * @mbggenerated
     */
    public String getTeachId() {
        return teachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.teach_id
     *
     * @param teachId the value for link.teach_id
     *
     * @mbggenerated
     */
    public void setTeachId(String teachId) {
        this.teachId = teachId == null ? null : teachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.start_time
     *
     * @return the value of link.start_time
     *
     * @mbggenerated
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.start_time
     *
     * @param startTime the value for link.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.end_time
     *
     * @return the value of link.end_time
     *
     * @mbggenerated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.end_time
     *
     * @param endTime the value for link.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }
}