package com.spj.demo.pojo;

import java.util.Date;

public class Vote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_id
     *
     * @mbggenerated
     */
    private Integer voteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.start
     *
     * @mbggenerated
     */
    private Integer start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.teach_id
     *
     * @mbggenerated
     */
    private String teachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.course_id
     *
     * @mbggenerated
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_id
     *
     * @return the value of vote.vote_id
     *
     * @mbggenerated
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_id
     *
     * @param voteId the value for vote.vote_id
     *
     * @mbggenerated
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.start
     *
     * @return the value of vote.start
     *
     * @mbggenerated
     */
    public Integer getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.start
     *
     * @param start the value for vote.start
     *
     * @mbggenerated
     */
    public void setStart(Integer start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.reason
     *
     * @return the value of vote.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.reason
     *
     * @param reason the value for vote.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.teach_id
     *
     * @return the value of vote.teach_id
     *
     * @mbggenerated
     */
    public String getTeachId() {
        return teachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.teach_id
     *
     * @param teachId the value for vote.teach_id
     *
     * @mbggenerated
     */
    public void setTeachId(String teachId) {
        this.teachId = teachId == null ? null : teachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.course_id
     *
     * @return the value of vote.course_id
     *
     * @mbggenerated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.course_id
     *
     * @param courseId the value for vote.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.stu_id
     *
     * @return the value of vote.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.stu_id
     *
     * @param stuId the value for vote.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.time
     *
     * @return the value of vote.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.time
     *
     * @param time the value for vote.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}